//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JogoDoNilson.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Carta
    {
        public int Id { get; set; }
        public string Nome { get; set; }
        public int Custo { get; set; }
        public int Ataque { get; set; }
        public int Defesa { get; set; }
        public string Descricao { get; set; }
        public string Classe { get; set; }
        public string Raça { get; set; }
        public System.DateTime DataInclusao { get; set; }
        public bool Active { get; set; }
        public int classificacao { get; set; }
    
        public virtual ClassificacaoCarta jdn_ClassificacaoCarta { get; set; }
    }
}
