//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace JogoDoNilson.Models
{
    #region Contextos
    
    /// <summary>
    /// Nenhuma Documentação de Metadados disponível.
    /// </summary>
    public partial class JogoDoNilsonEntities : ObjectContext
    {
        #region Construtores
    
        /// <summary>
        /// Inicializa um novo objeto JogoDoNilsonEntities usando a cadeia de conexão localizada na seção 'JogoDoNilsonEntities' do arquivo de configuração do aplicativo.
        /// </summary>
        public JogoDoNilsonEntities() : base("name=JogoDoNilsonEntities", "JogoDoNilsonEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicialize um novo objeto JogoDoNilsonEntities.
        /// </summary>
        public JogoDoNilsonEntities(string connectionString) : base(connectionString, "JogoDoNilsonEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicialize um novo objeto JogoDoNilsonEntities.
        /// </summary>
        public JogoDoNilsonEntities(EntityConnection connection) : base(connection, "JogoDoNilsonEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Métodos Parciais
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Propriedades de ObjectSet
    
        /// <summary>
        /// Nenhuma Documentação de Metadados disponível.
        /// </summary>
        public ObjectSet<Carta> jdn_cartas
        {
            get
            {
                if ((_jdn_cartas == null))
                {
                    _jdn_cartas = base.CreateObjectSet<Carta>("jdn_cartas");
                }
                return _jdn_cartas;
            }
        }
        private ObjectSet<Carta> _jdn_cartas;

        #endregion

        #region Métodos AddTo
    
        /// <summary>
        /// Método preterido para adicionar um novo objeto ao EntitySet jdn_cartas. Em vez disso, experimente usar o método .Add da propriedade ObjectSet&lt;T&gt; associada.
        /// </summary>
        public void AddTojdn_cartas(Carta carta)
        {
            base.AddObject("jdn_cartas", carta);
        }

        #endregion

    }

    #endregion

    #region Entidades
    
    /// <summary>
    /// Nenhuma Documentação de Metadados disponível.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="JogoDoNilsonModel", Name="Carta")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Carta : EntityObject
    {
        #region Método de Fábrica
    
        /// <summary>
        /// Crie um novo objeto Carta.
        /// </summary>
        /// <param name="id">Valor inicial da propriedade Id.</param>
        /// <param name="nome">Valor inicial da propriedade Nome.</param>
        /// <param name="custo">Valor inicial da propriedade Custo.</param>
        /// <param name="ataque">Valor inicial da propriedade Ataque.</param>
        /// <param name="defesa">Valor inicial da propriedade Defesa.</param>
        /// <param name="raça">Valor inicial da propriedade Raça.</param>
        /// <param name="dataInclusao">Valor inicial da propriedade DataInclusao.</param>
        public static Carta CreateCarta(global::System.Int32 id, global::System.String nome, global::System.Int32 custo, global::System.Int32 ataque, global::System.Int32 defesa, global::System.String raça, global::System.DateTime dataInclusao)
        {
            Carta carta = new Carta();
            carta.Id = id;
            carta.Nome = nome;
            carta.Custo = custo;
            carta.Ataque = ataque;
            carta.Defesa = defesa;
            carta.Raça = raça;
            carta.DataInclusao = dataInclusao;
            return carta;
        }

        #endregion

        #region Propriedades Primitivas
    
        /// <summary>
        /// Nenhuma Documentação de Metadados disponível.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// Nenhuma Documentação de Metadados disponível.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nome
        {
            get
            {
                return _Nome;
            }
            set
            {
                OnNomeChanging(value);
                ReportPropertyChanging("Nome");
                _Nome = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Nome");
                OnNomeChanged();
            }
        }
        private global::System.String _Nome;
        partial void OnNomeChanging(global::System.String value);
        partial void OnNomeChanged();
    
        /// <summary>
        /// Nenhuma Documentação de Metadados disponível.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Custo
        {
            get
            {
                return _Custo;
            }
            set
            {
                OnCustoChanging(value);
                ReportPropertyChanging("Custo");
                _Custo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Custo");
                OnCustoChanged();
            }
        }
        private global::System.Int32 _Custo;
        partial void OnCustoChanging(global::System.Int32 value);
        partial void OnCustoChanged();
    
        /// <summary>
        /// Nenhuma Documentação de Metadados disponível.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Ataque
        {
            get
            {
                return _Ataque;
            }
            set
            {
                OnAtaqueChanging(value);
                ReportPropertyChanging("Ataque");
                _Ataque = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Ataque");
                OnAtaqueChanged();
            }
        }
        private global::System.Int32 _Ataque;
        partial void OnAtaqueChanging(global::System.Int32 value);
        partial void OnAtaqueChanged();
    
        /// <summary>
        /// Nenhuma Documentação de Metadados disponível.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Defesa
        {
            get
            {
                return _Defesa;
            }
            set
            {
                OnDefesaChanging(value);
                ReportPropertyChanging("Defesa");
                _Defesa = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Defesa");
                OnDefesaChanged();
            }
        }
        private global::System.Int32 _Defesa;
        partial void OnDefesaChanging(global::System.Int32 value);
        partial void OnDefesaChanged();
    
        /// <summary>
        /// Nenhuma Documentação de Metadados disponível.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Descricao
        {
            get
            {
                return _Descricao;
            }
            set
            {
                OnDescricaoChanging(value);
                ReportPropertyChanging("Descricao");
                _Descricao = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Descricao");
                OnDescricaoChanged();
            }
        }
        private global::System.String _Descricao;
        partial void OnDescricaoChanging(global::System.String value);
        partial void OnDescricaoChanged();
    
        /// <summary>
        /// Nenhuma Documentação de Metadados disponível.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Classe
        {
            get
            {
                return _Classe;
            }
            set
            {
                OnClasseChanging(value);
                ReportPropertyChanging("Classe");
                _Classe = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Classe");
                OnClasseChanged();
            }
        }
        private global::System.String _Classe;
        partial void OnClasseChanging(global::System.String value);
        partial void OnClasseChanged();
    
        /// <summary>
        /// Nenhuma Documentação de Metadados disponível.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Raça
        {
            get
            {
                return _Raça;
            }
            set
            {
                OnRaçaChanging(value);
                ReportPropertyChanging("Raça");
                _Raça = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Raça");
                OnRaçaChanged();
            }
        }
        private global::System.String _Raça;
        partial void OnRaçaChanging(global::System.String value);
        partial void OnRaçaChanged();
    
        /// <summary>
        /// Nenhuma Documentação de Metadados disponível.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DataInclusao
        {
            get
            {
                return _DataInclusao;
            }
            set
            {
                OnDataInclusaoChanging(value);
                ReportPropertyChanging("DataInclusao");
                _DataInclusao = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DataInclusao");
                OnDataInclusaoChanged();
            }
        }
        private global::System.DateTime _DataInclusao;
        partial void OnDataInclusaoChanging(global::System.DateTime value);
        partial void OnDataInclusaoChanged();

        #endregion

    
    }

    #endregion

    
}
